package com.hbc.demo1.dao;

import com.hbc.demo1.entity.Album;

public interface AlbumMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_album
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_album
     *
     * @mbggenerated
     */
    int insert(Album record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_album
     *
     * @mbggenerated
     */
    int insertSelective(Album record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_album
     *
     * @mbggenerated
     */
    Album selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_album
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Album record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_album
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Album record);
}