package com.hbc.demo1.entity;

import com.alibaba.fastjson.annotation.JSONField;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;
import java.util.Date;
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Album implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_album.id
     *
     * @mbggenerated
     */
    @JSONField(serialize = false)
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_album.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_album.cover_pic
     *
     * @mbggenerated
     */
    private String coverPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_album.author
     *
     * @mbggenerated
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_album.broadcaster
     *
     * @mbggenerated
     */
    private String broadcaster;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_album.score
     *
     * @mbggenerated
     */
    private Integer score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_album.count
     *
     * @mbggenerated
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_album.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_album.add_date
     *
     * @mbggenerated
     */
    private Date addDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_album
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_album.id
     *
     * @return the value of t_album.id
     *
     * @mbggenerated
     */

}